# Generated by Django 3.2.16 on 2022-11-30 17:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('dish_pic', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=300)),
                ('allergy_icon', models.CharField(choices=[('0', 'none'), ('1', 'cereal'), ('2', 'gluten'), ('3', 'milk'), ('4', 'eggs'), ('5', 'peanuts'), ('6', 'nuts'), ('7', 'crustaceans'), ('8', 'mustard'), ('9', 'fish'), ('11', 'lupin'), ('12', 'sesame'), ('13', 'celery'), ('14', 'soya'), ('15', 'molluscs')], default='0', max_length=12)),
                ('calorie_amount', models.CharField(max_length=6)),
                ('protien_amount', models.CharField(max_length=6)),
                ('carbs_amount', models.CharField(max_length=6)),
                ('fat_amount', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
