# Generated by Django 3.2.16 on 2022-11-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
